version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: djote_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DEBUG: '1'
      DB_NAME: djote_db
      DB_USER: postgres
      DB_PASSWORD: admin1234
      DB_HOST: db
      DB_PORT: 5432

volumes:
  postgres_data: