# Generated by Django 3.2 on 2024-04-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
