# Generated by Django 3.2 on 2024-04-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_authuser_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='authuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='none'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
